[workspace]
authors = ["umerkhan95 <96595386+umerkhan95@users.noreply.github.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
name = "mojo-gateway"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]
dev = "mojo run src/main.mojo"
build = "mojo build src/main.mojo -o bin/gateway"

[dependencies]
max = ">=25.1"
